<!DOCTYPE html>
<html>
    <head>
        <title><?php echo $this->data["title"] ?></title>
        <link href="css/bootstrap.css" type="text/css" rel="stylesheet" media="all">
        <link href="css/style.css" type="text/css" rel="stylesheet" media="all">
        <link href="css/main.css" type="text/css" rel="stylesheet" media="all">
        <link rel="stylesheet" href="assets/font-awesome/css/font-awesome.min.css">
		<link rel="stylesheet" href="assets/css/form-elements.css">
        <!--link rel="stylesheet" href="assets/css/style.css"-->

        <!-- Custom Theme files -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="keywords" "Ontario Mater Gardeners Kitchener Master Gardeners flowers" />

        <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
        <!-- //Custom Theme files -->
        <!-- js -->
        <script src="js/jquery-1.11.1.min.js"></script>
        <!-- //js -->
        <!-- start-smoth-scrolling-->
        <script type="text/javascript" src="js/move-top.js"></script>
        <script type="text/javascript" src="js/easing.js"></script>
        <script type="text/javascript" src="js/sha512.js"></script>
        <script type="text/javascript" src="js/angular.min.js"></script>
        <script type="text/javascript" src="js/angular-route.min.js"></script>
        <script type="text/javascript">
            jQuery(document).ready(function($) {
                $(".scroll").click(function(event){
                    event.preventDefault();
                    $('html,body').animate({scrollTop:$(this.hash).offset().top},1000);
                });
            });
        </script>
        <!--//end-smoth-scrolling-->
    </head>
    <body>
        <!--header-->
        <div class="logo">
            <div class="container">
                <div class="logo-info">
                    <img src="http://www.mgoi.ca/rw_common/images/MGOI-logo240x160-newest.jpg" width="240" height="160" alt="Site logo" class="imglogo">
                    <a href="index.html"> <h1>Kitchener Master Gardeners</h1></a>
                </div>
            </div>
        </div>

        <!--=======================================================navigation bar===========================-->
        <div class="top-nav">
            <nav class="navbar navbar-default">
                <div class="container">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">Menu
				    </button>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav">
                            <li </li>
                            <li class="hvr-bounce-to-bottom <?php if($this->sPage == "index.phtml") echo "active" ?>"><a href="index">Home</a></li>
                            <li class="hvr-bounce-to-bottom <?php if($this->sPage == "about.phtml") echo "active" ?>"><a href="about">About</a></li>
                            <li class="hvr-bounce-to-bottom <?php if($this->sPage == "calendar.phtml") echo "active" ?>"><a href="calendar">Activities</a></li>
                            <li class="hvr-bounce-to-bottom <?php if($this->sPage == "contact.phtml") echo "active" ?>"><a href="contact">Contact Us</a></li>
                            <li class="hvr-bounce-to-bottom <?php if($this->sPage == "login.phtml") echo "active" ?>"><a href="login">Login</a></li>
                        </ul>
                        <div class="clearfix"> </div>
                    </div>

            </nav>
        </div>
        <!--=============================================================navigation =======================================-->

        <?php $this->renderBody(); ?>

        <!-- footer -->
        <div class="footer">
            <div class="container">
                <div class="footer-grids">
                    <div class="col-md-3 footer-grid">
                        <h3 class="title">External Links</h3>
                        <ul>
                            <li><a href="http://www.mgoi.ca/">Ontario Master Garderners</a></li>
                            <li><a href="http://www.kitchenerhs.ca/cms/">Kitchener Horticulutural Society</a></li>
                        </ul>
                    </div>
 <div class="col-md-3 footer-grid">
                        <h3 class="title">Send Us an email</h3>
                        <ul>
                                 <li><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span><a href="mailto:kgardener2002@gmail.com">kgardener2002@gmail.com</a></li>
                        </ul>
                    </div>



                    <div class="clearfix"> </div>
                </div>
            </div>
        </div>
        <div class="copy">
            <div class="container">
                <div class="copy-left">
                    <p>Kitchener Master Gardeners © 2016. All rights reserved</p>
                </div>
                <div class="social-icons">
                    <ul>
					<li><a href="https://m.facebook.com/Kitchener-Master-Gardeners-1042458352480005/?ref=m_notif&notif_t=page_fan&actorid=100003644493969&notif_id=1458305449180731" class="fb"></a></li>
					<li><a href="#"></a></li>
					<li><a href="https://www.google.ca/?gfe_rd=cr&ei=0y0DV8fcIqaC8QefjZPICw#q=master%20gardeners%20of%20ontario" class="gg"></a></li>
					<li><a href="#" class="pn"></a></li>
				</ul>

                </div>
                <div class="clearfix"> </div>
            </div>
        </div>
        <!--//footer-->
        <!--smooth-scrolling-of-move-up-->
        <script type="text/javascript">
            $(document).ready(function() {
                /*
			var defaults = {
				containerID: 'toTop', // fading element id
				containerHoverID: 'toTopHover', // fading element hover id
				scrollSpeed: 1200,
				easingType: 'linear'
			};
			*/

                $().UItoTop({ easingType: 'easeOutQuart' });

            });
        </script>
        <a href="#" id="toTop" style="display: block;"> <span id="toTopHover" style="opacity: 1;"> </span></a>
        <!--//smooth-scrolling-of-move-up-->
        <!-- Bootstrap core JavaScript
================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->

        <!--//Oscar start  navigation slider javaScript This part must to be here-->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
		<script type="text/javascript">
			var indicador = 0;
			$(document).on('ready', function(){
				$('.left').on('click', function(e){
					e.preventDefault();
					moveSlider('left');
				});
				$('.right').on('click', function(e){
					e.preventDefault();
					moveSlider('right');
				});
				function auto(){
					intv = setInterval(function(){
					$('.right').click();
					}, 3000);
				}
				auto(); // start
				$('.form_container').hover(function( e ){
					return e.type=='mouseenter'?clearInterval(intv):auto();
				});
				defineSizes();
			});

			$(window).on('resize', defineSizes);
				function defineSizes(){
					$('.form_container .slide').each(function(i, el) {
						$(el).css({
							'background-image': 'url('+$(el).data('background')+')',
							'height': ($('.form_container').width() * 0.42)+'px',
							'width' : ($('.form_container').width())+'px'
						});
					});
				$('.form_container .slideContainer').css({
					'margin-left': -(indicador * $('.form_container').width())+'px'
				})
				}
			function moveSlider(direccion){
				var limite = $('.form_container .slide').length;
				indicador = (direccion == 'right') ? indicador + 1 : indicador - 1;
				indicador = (indicador >= limite) ? 0 : indicador;
				indicador = (indicador < 0) ? limite - 1 : indicador;
				$('.form_container .slideContainer').animate({
					'margin-left': -(indicador * $('.form_container').width())+'px'
				})
			}
		</script>

<!--//Oscar end  navigation slider javaScript This part must to be here-->

<!--===================================================================== -->



    </body>
</html>
