<?php
$this->data["title"] = "Kitchener Master Gardeners";
$this->layout("_layout.phtml");
?>
<!--baner-->
<div class="baner">
    <div class="container">
        <div class="baner-grids">
            <div class="col-md-6 baner-top">
					<figure class="effect-bubba">
						<img src="images/dahlia.png" alt="gerbera flower"/>
						<figcaption>
							<h4>Learn about different flowers</h4>
							<p>Flowers make you happy and make you feel good.</p>
						</figcaption>
					</figure>
            </div>
            <div class="col-md-6 baner-top">
					<figure class="effect-bubba">
						<img src="images/PurpleConeflower.png" alt=""/>
						<figcaption>
							<h4>Learn about the crops</h4>
							<p>Grow fresh veggies and crops in your own backyard.</p>
						</figcaption>
					</figure>
            </div>
            <div class="clearfix"> </div>
            <div class="baner-row">
                <div class="col-md-4 baner-bottom">
                    <figure class="effect-bubba">
                        <img src="images/three.jpg" alt=""/>
                        <figcaption>
                            <h4>Learn about kitchen gardening</h4>
                            <p>You can know more about Kitchen gardening concepts.</p>
                        </figcaption>
                    </figure>
                </div>
                <div class="col-md-4 baner-bottom">
                    <figure class="effect-bubba">
                        <img src="images/four.png" alt=""/>
                        <figcaption>
                            <h4>Learn how to make your garden beautiful</h4>
                            <p>In sit amet sapien eros Integer dolore magna aliqua</p>
                        </figcaption>
                    </figure>
                </div>
                <div class="col-md-4 baner-bottom">
                    <figure class="effect-bubba">
                        <img src="images/begonia.png" alt=""/>
                        <figcaption>
                            <h4>Learn to be pro in gardening</h4>
                            <p>In sit amet sapien eros Integer dolore magna aliqua</p>
                        </figcaption>
                    </figure>
                </div>
                <div class="clearfix"> </div>
            </div>
        </div>
    </div>
</div>
<!--//baner-->
<!-- news -->
<div class="news-info">
    <div class="container">
        <h3 class="title">OUR HISTORY</h3>
    </div>
</div>
<!-- container -->
<div class="container">
    <div class="news">
        <div class="news-grids">
            <div class="col-md-4 news-grid">
                <div class="news-grid-left news-grid-left-img">
                    <h6>The Canadian Cultivar</h6>
                </div>
                <div class="news-grid-left-info">
                    <h5 style="text-align:justify;">The first Master Gardener program began in the state of Washington in 1972. Dr. David Gibby, a horticultural extension agent, created the program in response to an overwhelming number of requests for gardening information from the public. Volunteers enlisted and trained in horticulture to provide gardening information to home gardeners. Master Gardener programs now operate in forty-five states and nine provinces in Canada.</h5>
                </div>
            </div>
            <div class="col-md-4 news-grid">
                <div class="news-grid-left news-grid-middle">
                    <h6>Master Gardeners of Ontario</h6>
                </div>
                <div class="news-grid-left-info">
                    <h5 style="text-align:justify;">he Master Gardener program is started in Ontario, sponsored by the Ontario Ministry of Agriculture, Food and Rural Affairs (OMAFRA) to provide unbiased, scientific horticultural information to the public, but not to deal with commercial or farm questions. Experienced gardeners are recruited by local horticultural societies. To form a group, the local horticultural society is approached and a presentation made about the MG program.</h5>

                </div>
            </div>

            <div class="col-md-4 news-grid">
                <div class="news-grid-left news-grid-right">
                    <h6>Master Gardeners 1995 to present day </h6>
                </div>
                <div class="news-grid-left-info">
                    <h5>Funding soon becomes a challenge. Corporate and foundation sponsorship does not meet needs. Member dues are the only way to continue the Master Gardener organization.
-At the time of incorporation there are 36 Master Gardener groups with over 800 active volunteers who are contributing nearly 35,000 hours of volunteer time to the program. </h5>

                </div>
            </div>
            <div class="clearfix"> </div>
        </div>
    </div><!-- //container -->
</div>
<!-- //news -->
<!--main-->
<div class="main">
    <div class="container">
        <div class="main-grids">
            <div class="col-md-6 main-left">
                <img src="images/img6.jpg" alt=""/>
                <h4 style="font-weight:bold;">TIPS ON GROWING VEGETABLES</h4>
                <h4 style="text-align:justify;">Since you are new to this type of gardening, however, you might be better off starting out with something smaller. Consider growing your garden in small beds or even containers. These alternatives work especially well if your space is quite limited. When you have a general idea about what you want, plan accordingly.</h4>
                <a href="http://www.gardeningknowhow.com/edible/vegetables/vgen/vegetable-gardening-for-beginners.htm" class="more btn btn-1 btn-1b"> Read More</a>
            </div>
            <div class="col-md-6 main-right">
                <div class="col-md-6 main-text">
                    <img src="images/img7.jpg" alt=""/>
                </div>
                <div class="col-md-6 main-text">
                    <h4 style="font-weight:bold;">ECO SOLUTIONS</h4>
                    <h4 style="text-align:justify;">Create an eco-friendly by using native plants, conserving water, and reducing pollution in water. An eco-friendly garden is all about designing with nature and the environment in mind.  Learn how to create a functional garden.</h4>
                    <a href="http://extension.psu.edu/plants/gardening/eco-friendly" class="more btn btn-1 btn-1b"> Read More</a>
                </div>
                <div class="clearfix"> </div>
            </div>
            <div class="clearfix"> </div>
        </div>
    </div>
</div>
<!--//main-->
<!--services-->
<div class="services" id="services">
    <div class="container">
        <h3 class="title">Other Services</h3>
        <div class="service-grids">
            <div class="col-md-4 srvc-grids-info">
                <div class="srvc-img">
                    <a href="http://www.mgoi.ca/education/workshops.html"><span class="glyphicon glyphicon-education" aria-hidden="true"></span></a>
                </div>
                <h5>Workshops</h5>
                <p>See Ontario uncoming workshops</p>
            </div>
            <div class="col-md-4 srvc-grids-info">
                <div class="srvc-img">
                    <a href="http://www.mgoi.ca/education/conferences.html"><span class="glyphicon glyphicon-bullhorn" aria-hidden="true"></span></a>
                </div>
                <h5>Conferences</h5>
                <p>Upcoming conferences </p>
            </div>
            <div class="col-md-4 srvc-grids-info">
                <div class="srvc-img">
                    <a href="http://www.mgoi.ca/news/newsblog.php"><span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span></a>
                </div>
                <h5>Ontario Gardeners News</h5>
                <p>Ontario Master Gardeners News Blog</p>
            </div>
            <div class="col-md-4 srvc-grids-info">
                <div class="srvc-img">
                    <a href="http://www.mgoi.ca/resources/resources.html#tabContent3_stacks_in_620_page13"><span class="glyphicon glyphicon-grain" aria-hidden="true"></span></a>
                </div>
                <h5>References</h5>
                <p>Education references</p>
            </div>
            <div class="col-md-4 srvc-grids-info">
                <div class="srvc-img">
                    <a href="http://www.mgoi.ca/resources/resources.html#tabContent4_stacks_in_620_page13"><span class="glyphicon glyphicon-wrench" aria-hidden="true"></span></a>
                </div>
                <h5>Resources</h5>
                <p>Ontario resources</p>
            </div>
            <div class="col-md-4 srvc-grids-info">
                <div class="srvc-img">
                    <a href="http://www.mgoi.ca/education/referencemanual.html"><span class="glyphicon glyphicon-folder-open" aria-hidden="true"></span></a>
                </div>
                <h5>Manual</h5>
                <p>Ontario Mastener Gardeners Reference Manual</p>
            </div>
            <div class="clearfix"> </div>
        </div>
    </div>
</div>
<!--//services-->
