<?php
$this->data["title"] = "Kitchener Master Gardeners";
$this->layout("_layout.phtml");
?>

<!--//Oscar start  navigation slider-->
<div>
    <div class="form_container">
        <div class="slideContainer">
            <div class="slide" data-background="images/img/one.jpg">
            </div>
            <div class="slide" data-background="images/img/two.jpg">
            </div>
            <div class="slide" data-background="images/img/three.jpg">
            </div>
            <div class="slide" data-background="images/img/four.jpg">
            </div>
            <div class="slide" data-background="images/img/five.jpg">
            </div>
            <div class="slide" data-background="images/img/six.jpg">
            </div>
            <div class="slide" data-background="images/img/seven.jpg">
            </div>
            <div class="slide" data-background="images/img/eight.jpg">
            </div>
        </div>
        <div class="left"></div>
        <div class="right"></div>
    </div>
</div>
<!--//Oscar end  navigation slider-->
<!--about-->
<div class="about">
    <div class="container">
        <h3 class="title">Our History</h3>
        <div class="about-text">
            <div class="col-md-6 about-text-left">
                <img src="images/a.jpg" class="img-responsive" alt=""/>
            </div>
            <div class="col-md-6 about-text-right">
                <h4>THE CANADIAN CULTIVAR</h4>
                <p align="justify">The first Master Gardener program began in the state of Washington in 1972. Dr. David Gibby, a horticultural extension agent, created the program in response to an overwhelming number of requests for gardening information from the public. Volunteers enlisted and trained in horticulture to provide gardening information to home gardeners. Master Gardener programs now operate in forty-five states and nine Canadian provinces.</p>
                <p align="justify">In 1987, the high level of interest led to the first national Master Gardener Conference in Washington, D.C. A second national conference was held in Portland Oregon in 1989. In 1991, Master Gardeners from Ontario and Michigan hosted the first international Master Gardener Conference in Detroit followed by subsequent conferences in San Antonio (1993) and Saskatoon (1995). At this time, the International Master Gardener Conference is held every other year at different locations.</p>

            </div>
            <div class="clearfix"> </div>
        </div>
    </div>
    <div class="about-slid">
        <div class="container">
            <div class="about-slid-info">
                <h2>Want to be a member</h2>
                <p>Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet embarrassing hidden in the middle of text.</p>
            </div>
        </div>
    </div>
</div>
<div class="about-team">
    <div class="container">
        <h3 class="title">More About Us</h3>
        <div class="row team-row">
            <div class="col-sm-6 col-md-3 team-grids">
                <div class="thumbnail team-thmnl">
                    <img src="images/a.jpg" class="img-responsive zoom-img" alt="...">
                    <div class="caption">
                        <h4><a href="#">vaura tegsner</a></h4>
                        <p>Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary</p>
                    </div>
                </div>
            </div>
            <div class="col-sm-6 col-md-3 team-grids">
                <div class="thumbnail team-thmnl">
                    <img src="images/b.jpg" class="img-responsive zoom-img" alt="...">
                    <div class="caption">
                        <h4><a href="#">Jark Kohnson</a></h4>
                        <p>Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary</p>
                    </div>
                </div>
            </div>
            <div class="col-sm-6 col-md-3 team-grids">
                <div class="thumbnail team-thmnl">
                    <img src="images/e.jpg" class="img-responsive zoom-img" alt="...">
                    <div class="caption">
                        <h4><a href="#">goes mehak</a></h4>
                        <p>Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary</p>
                    </div>
                </div>
            </div>
            <div class="col-sm-6 col-md-3 team-grids">
                <div class="thumbnail team-thmnl">
                    <img src="images/c.jpg" class="img-responsive zoom-img" alt="...">
                    <div class="caption">
                        <h4><a href="#">Jark Kohnson</a></h4>
                        <p>Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary</p>
                    </div>
                </div>
            </div>
            <div class="clearfix"> </div>
        </div>
    </div>
</div>

