<?php
$this->data["title"] = "Kitchener Master Gardeners";
$this->layout("_layout.phtml");
?>
<script>

    angular.module('myApp', []).controller("myController", function ($scope, $http) {
        $http.get("/users").success(function(oData){
            for(var i = 0; i < oData.length; i++){
                if(oData[i].bPending == 1)oData[i].bPending = true;
                else oData[i].bPending = false;
                if(oData[i].bAdmin == 1)oData[i].bAdmin = true;
                else oData[i].bAdmin = false;
                if(oData[i].bVolunteer == 1)oData[i].bVolunteer = true;
                else oData[i].bVolunteer = false;
            }
            $scope.users = oData;
        });
        $scope.onChange = function(user){
            $http.post("/users", user).success(function(oData){
                console.log(oData);
                toastr.info('saved');
            })
            .error(function(oData){
                console.log(oData);
                toastr.error('not saved' + JSON.stringify(oData));

            });
        };
    });
</script>
<div ng-app="myApp" ng-controller="myController" class="contact">
    <div class="container">
        <h3 class="title">General Inquiries</h3>
    </div>
    <div class="baner-grids">
        <div class="contact-form">
            <div class="news">
                <div class="text">
                    <h3>Members Information</h3>
                </div>
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Message</th>
                            <th>Pending</th>
                            <th>Admin</th>
                            <th>Volunteer</th>

                        </tr>
                    </thead>
                    <tbody>
                        <tr ng-repeat="(n, user) in users track by n" ng-cloak>
                            <td>{{user.name}}</td>
                            <td>{{user.message}}</td>
                            <td><input type="checkbox" ng-model="user.bPending" ng-change="onChange(user)" /></td>
                            <td><input type="checkbox" ng-model="user.bAdmin" ng-change="onChange(user)" /></td>
                            <td><input type="checkbox" ng-model="user.bVolunteer" ng-change="onChange(user)" /></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>




