<?php
$this->data["title"] = "Kitchener Master Gardeners";
$this->layout("_layout.phtml");
?>
<script>

    angular.module('myApp', []).controller("myController", function ($scope, $http) {
        $http.get("/users").success(function(oData){
            for(var i = 0; i < oData.length; i++){
                if(oData[i].bPending == "true")oData[i].bPending = true;
                else oData[i].bPending = false;
                if(oData[i].bAdmin == "true")oData[i].bAdmin = true;
                else oData[i].bAdmin = false;
                if(oData[i].bVolunteer == "true")oData[i].bVolunteer = true;
                else oData[i].bVolunteer = false;
            }
            $scope.users = oData;
        });
    });
</script>
<div ng-app="myApp" ng-controller="myController" class="contact">
    <div class="container">
        <h3 class="title">General Inquiries</h3>
    </div>
    <div class="baner-grids">
        <div class="contact-form">
            <div class="news">
                <div class="text">
                    <h3>Members Information</h3>
                </div>
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Pending</th>
                            <th>Admin</th>
                            <th>Volunteer</th>

                        </tr>
                    </thead>
                    <tr ng-repeat="(n, user) in users track by n" ng-cloak>
                        <td>{{user.name}}</td>
                        <td><input type="checkbox" ng-model="user.bPending" /></td>
                        <td><input type="checkbox" ng-model="user.bAdmin" /></td>
                        <td><input type="checkbox" ng-model="user.bVolunteer" /></td>
                    </tr>

                </table>
            </div>
        </div>
    </div>
</div>




