<?php
$this->data["title"] = "Kitchener Master Gardeners";
$this->layout("_layout.phtml");
?>
<body>

	<!--//navigation-->
	<!--baner-->
	<div class="baner about-bnr">
		<div class="container">
			<div class="baner-grids">
				<div class="col-md-6 baner-top">
					<img src="images/img16.jpg" alt=""/>
				</div>
				<div class="col-md-6 baner-top">
					<img src="images/img17.jpg" alt=""/>
				</div>
				<div class="clearfix"> </div>
			</div>
		</div>
	</div>
	<!--//baner-->
	<!--gallery-->


	<div class="gallery">
		<iframe class="calendar" width="62%" height="450" frameborder="10" src="https://calendar.google.com/calendar/embed?src=e3g4m23qejlb7337i3qigi1umc%40group.calendar.google.com&ctz=America/Toronto" style="border: 0" width="800" height="600" frameborder="0" scrolling="no"></iframe>
	</div>
	<!--//gallery-->
	<!-- footer -->
	<div class="footer">
		<div class="container">
			<div class="footer-grids">
				<div class="col-md-3 footer-grid">
					<h3 class="title">Services</h3>
					<ul>
						<li><a href="#">Rerum hic tenetur</a></li>
						<li><a href="#">Molestiae non recusandae</a></li>
						<li><a href="#">Voluptates repudiandae</a></li>
						<li><a href="#">Necessitatibus saepe</a></li>
						<li><a href="#">Debitis aut rerum</a></li>
					</ul>
				</div>
				<div class="col-md-3 footer-grid">
					<h3 class="title">Information</h3>
					 <ul>
						<li><a href="#">Quibusdam et aut</a></li>
						<li><a href="#">Testimonals</a></li>
						<li><a href="#">Archives</a></li>
						<li><a href="#">Our Staff</a></li>
					</ul>
				</div>
				<div class="col-md-3 footer-grid">
					<h3 class="title">More details</h3>
					<ul>
						<li><a href="about.html">About us</a></li>
						<li><a href="#">Privacy Policy</a></li>
						<li><a href="#">Terms &amp; Conditions</a></li>
						<li><a href="contact.html">Site map</a></li>
					</ul>
				</div>
				 <div class="col-md-3 footer-grid contact-grid">
						<h3 class="title">Contact us</h3>
						<ul>
							<li><span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span>Newyork Still Road.</li>
							<li class="adrs">756 gt globel Place</li>
							<li><span class="glyphicon glyphicon-earphone" aria-hidden="true"></span>+000 100 444 1111</li>
							<li><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span><a href="mailto:example@mail.com">mail@example.com</a></li>
						</ul>
				 </div>
				 <div class="clearfix"></div>
			</div>
		</div>
	</div>
	<div class="copy">
		<div class="container">
			<div class="copy-left">
				<p>Copyright © 2015 Crops. All rights reserved | Design by <a href="http://w3layouts.com">W3layouts</a></p>
			</div>
			<div class="social-icons">
				<ul>
					<li><a href="#" class="fb"></a></li>
					<li><a href="#"></a></li>
					<li><a href="#" class="gg"></a></li>
					<li><a href="#" class="pn"></a></li>
				</ul>
			</div>
			<div class="clearfix"> </div>
		</div>
	</div>
	<!--//footer-->
	<!-- start-smoth-scrolling-->
	<script type="text/javascript" src="js/move-top.js"></script>
	<script type="text/javascript" src="js/easing.js"></script>
	<script type="text/javascript">
			jQuery(document).ready(function($) {
				$(".scroll").click(function(event){
					event.preventDefault();
					$('html,body').animate({scrollTop:$(this.hash).offset().top},1000);
				});
			});
	</script>
	<!--//end-smoth-scrolling-->
	<!--smooth-scrolling-of-move-up-->
	<script type="text/javascript">
		$(document).ready(function() {
			/*
			var defaults = {
				containerID: 'toTop', // fading element id
				containerHoverID: 'toTopHover', // fading element hover id
				scrollSpeed: 1200,
				easingType: 'linear'
			};
			*/

			$().UItoTop({ easingType: 'easeOutQuart' });

		});
	</script>
	<a href="#" id="toTop" style="display: block;"> <span id="toTopHover" style="opacity: 1;"> </span></a>
	<!--//smooth-scrolling-of-move-up-->
	<!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="js/bootstrap.js"></script>
</body>
</html>
