
<?php
$this->data["title"] = "Kitchener Master Gardeners";
$this->layout("_layout.phtml");
?>
<body>

        <!--baner-->
        <div class="baner about-bnr">
            <div class="container">
                <div class="baner-grids">
                    <div class="col-md-6 baner-top">
                        <img src="images/img16.jpg" alt=""/>
                    </div>
                    <div class="col-md-6 baner-top">
                        <img src="images/img17.jpg" alt=""/>
                    </div>
                    <div class="clearfix"> </div>
                </div>
            </div>
        </div>
        <!--//baner-->


        <!--//map-->
        <!--contact-->
    <div class="contact">
        <div class="container">
            <h3 class="title">Contact us</h3>

                <div class="baner-grids">
                    <div class="contact-form">
                        <div class="news">
                            <div class="text">
                            <h3>If you have any gardening question, please fill in the form below and we’ll reply as soon as possible.</h3>
                            </div>
                            <form>
                                <input type="text" value="Name" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Name';}" required="">
                                <div class="col-md-6 cnt-inpt">
                                <input type="email" value="Email" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Email';}" required="">
                                </div>
                                <div class="col-md-6 cnt-inpt">
                                <input type="text" value="Telephone" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Telephone';}" required="">
                                </div>
                                <div class="clearfix"> </div>
                                <textarea onfocus="this.value = '' ;" onblur="if (this.value == '') {this.value = 'Message...';}" required=""> Message... </textarea>
                                <input type="submit" value="Submit">
                            </form>

                        </div>
                    </div>
                </div>
        </div>
    </div>
     <!--//contact-->
        <div class="row">
                        <div class="col-sm-6 col-sm-offset-3 social-login">
                        	<h3>...or login with:</h3>
                        	<div class="social-login-buttons">
	                        	<a class="btn btn-link-1 btn-link-1-facebook" href="http://m.facebook.com/Kitchener-Master-Gardeners-10424583522480005">
	                        		<i class="fa fa-facebook"></i> Facebook
	                        	</a>
	                        	<a class="btn btn-link-1 btn-link-1-twitter" href="#">
	                        		<i class="fa fa-twitter"></i> Twitter
	                        	</a>

                        	</div>
                        </div>
        </div>
        <!--//contact-->

        <!--smooth-scrolling-of-move-up-->
        <script type="text/javascript">
            $(document).ready(function() {
                /*
			var defaults = {
				containerID: 'toTop', // fading element id
				containerHoverID: 'toTopHover', // fading element hover id
				scrollSpeed: 1200,
				easingType: 'linear'
			};
			*/

                $().UItoTop({ easingType: 'easeOutQuart' });

            });
        </script>
        <a href="#" id="toTop" style="display: block;"> <span id="toTopHover" style="opacity: 1;"> </span></a>
        <!--//smooth-scrolling-of-move-up-->
        <!-- Bootstrap core JavaScript
================================================== -->

</body>

