
<?php
$this->data["title"] = "Kitchener Master Gardeners";
$this->layout("_layout.phtml");
?>
<script>
    angular.module('myApp', []).controller("myController", function ($scope, $http) {
        $scope.sendMail = function(){
            var oMessage = {};
            oMessage.email = $scope.message.email;
            oMessage.subject = "Inquiry from " + $scope.message.firstName + " " + $scope.message.secondName + " Number: " + $scope.message.phone;
            oMessage.message = $scope.message.message;
            $http({method: 'GET', url: 'https://rich-hildred.rhcloud.com/Mailer/c512c9f7', params: oMessage}).success(function(oData){
                console.log(oData);
                toastr.info(oData.result);
                $scope.message = {};
            }).
            error(function(oData){
                console.log(oData);
                toastr.error(JSON.stringify(oData));
            });
        };
    });
</script>


<body>

        <!--baner-->
        <div class="baner about-bnr">
            <div class="container">
                <div class="baner-grids">
                    <div class="col-md-6 baner-top">
                        <img src="images/wild_ asters.png" alt=""/>
                    </div>
                    <div class="col-md-6 baner-top">
                        <img src="images/victoriagardens.png" alt=""/>
                    </div>
                    <div class="clearfix"> </div>
                </div>
            </div>
        </div>
        <!--//baner-->

        <!--contact-->
    <div class="contact"  ng-app="myApp" ng-controller="myController" >
        <div class="container">
            <h3 class="title">Contact us</h3>
                <div class="news">
                    <div class="baner-grids">
                        <div class="contact-form">
                        <div class="text">
                           <h3>If you have any gardening question, please fill in the form below and we’ll reply as soon as possible.</h3>
                        </div>
                         <form ng-submit="sendMail()">
                            <input type="text" placeholder="First name" required="" ng-model="message.firstName" />
                            <input type="text" placeholder="Last name" required="" ng-model="message.secondName" />
                            <div class="col-md-6 cnt-inpt">
                            <input type="email" placeholder="Email" required="" ng-model="message.email" />
                            </div>
                            <div class="col-md-6 cnt-inpt">
                            <input type="text" placeholder="Phone number" ng-model="message.phone" />
                            </div>
                            <div class="clearfix"> </div>
                            <textarea placeholder="Message..." required="" ng-model="message.message"></textarea>
                            <input type="submit" value="Submit" >
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
     <!--//contact-->
        <div class="row">
                        <div class="col-sm-6 col-sm-offset-3 social-login">
                        	<h3>...or login with:</h3>
                        	<div class="social-login-buttons">
	                        	<a class="btn btn-link-1 btn-link-1-facebook" href="http://m.facebook.com/Kitchener-Master-Gardeners-10424583522480005">
	                        		<i class="fa fa-facebook"></i> Facebook
	                        	</a>
	                        	<a class="btn btn-link-1 btn-link-1-twitter" href="#">
	                        		<i class="fa fa-twitter"></i> Twitter
	                        	</a>

                        	</div>
                        </div>
        </div>
        <!--//contact-->

        <!--smooth-scrolling-of-move-up-->
        <script type="text/javascript">
            $(document).ready(function() {
                /*
			var defaults = {
				containerID: 'toTop', // fading element id
				containerHoverID: 'toTopHover', // fading element hover id
				scrollSpeed: 1200,
				easingType: 'linear'
			};
			*/

                $().UItoTop({ easingType: 'easeOutQuart' });

            });
        </script>
        <a href="#" id="toTop" style="display: block;"> <span id="toTopHover" style="opacity: 1;"> </span></a>
        <!--//smooth-scrolling-of-move-up-->
        <!-- Bootstrap core JavaScript
================================================== -->

</body>

