<?php
$this->data["title"] = "Kitchener Master Gardeners";
$this->layout("_layout.phtml");
?>

<!--//Oscar start  navigation slider-->
<div>
    <div class="form_container">
        <div class="slideContainer">
            <div class="slide" data-background="images/img/one.jpg">
            </div>
            <div class="slide" data-background="images/img/two.jpg">
            </div>
            <div class="slide" data-background="images/img/three.jpg">
            </div>
            <div class="slide" data-background="images/img/four.jpg">
            </div>
            <div class="slide" data-background="images/img/five.jpg">
            </div>
            <div class="slide" data-background="images/img/six.jpg">
            </div>
            <div class="slide" data-background="images/img/seven.jpg">
            </div>
            <div class="slide" data-background="images/img/eight.jpg">
            </div>
        </div>
        <div class="left"></div>
        <div class="right"></div>
    </div>
</div>
<!--//Oscar end  navigation slider-->
<!--about-->
<div class="about">
    <div class="container">
        <h3 class="title">Welcome to the Kitchener Master Gardeners of Ontario Inc. Website!
        </h3>
        <div class="about-text">
            <div class="col-md-6 about-text-left">
                <img src="images/a.jpg" class="img-responsive" alt=""/>
            </div>
            <div class="col-md-6 about-text-right">
                <h4>KITCHENER MASTER GARDENERS</h4>
                <p align="justify">We are an independent non-profit organization dedicated to helping home gardeners.
                </p>
                <p align="justify">Master Gardeners (MGs) in the Province of Ontario are experienced gardeners who have studied horticulture extensively and continue to upgrade their skills through technical training. With this training and continuing education, Master Gardeners provide expert horticultural advice to the general public.</p>

            </div>
            <div class="clearfix"> </div>
        </div>
    </div>
    <div class="about-slid">
        <div class="container">
            <div class="about-slid-info">
                <h2><a href="http://www.mgoi.ca/education.html">To become a Master Gardener:</a></h2>
            </div>
        </div>
    </div>
</div>
<div class="about-team">
    <div class="container">
        <h3 class="title">More About Us</h3>
        <div class="row team-row">
            <div class="col-sm-6 col-md-3 team-grids">
                <div class="thumbnail team-thmnl">
                    <img src="images/a.jpg" class="img-responsive zoom-img" alt="...">
                    <div class="caption">
                        <h4><a href="#">vaura tegsner</a></h4>
                        <p>Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary</p>
                    </div>
                </div>
            </div>
            <div class="col-sm-6 col-md-3 team-grids">
                <div class="thumbnail team-thmnl">
                    <img src="images/b.jpg" class="img-responsive zoom-img" alt="...">
                    <div class="caption">
                        <h4><a href="#">Jark Kohnson</a></h4>
                        <p>Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary</p>
                    </div>
                </div>
            </div>
            <div class="col-sm-6 col-md-3 team-grids">
                <div class="thumbnail team-thmnl">
                    <img src="images/e.jpg" class="img-responsive zoom-img" alt="...">
                    <div class="caption">
                        <h4><a href="#">goes mehak</a></h4>
                        <p>Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary</p>
                    </div>
                </div>
            </div>
            <div class="col-sm-6 col-md-3 team-grids">
                <div class="thumbnail team-thmnl">
                    <img src="images/c.jpg" class="img-responsive zoom-img" alt="...">
                    <div class="caption">
                        <h4><a href="#">Jark Kohnson</a></h4>
                        <p>Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary</p>
                    </div>
                </div>
            </div>
            <div class="clearfix"> </div>
        </div>
    </div>
</div>

