<?php
$this->data["title"] = "Kitchener Master Gardeners";
$this->layout("_layout.phtml");
?>

<!--//Oscar start  navigation slider-->
<div>
    <div class="form_container">
        <div class="slideContainer">
            <div class="slide" data-background="images/img/one.jpg">
            </div>
            <div class="slide" data-background="images/img/crocus.jpg">
            </div>
            <div class="slide" data-background="images/img/three.jpg">
            </div>
            <div class="slide" data-background="images/img/four.jpg">
            </div>
            <div class="slide" data-background="images/img/five.jpg">
            </div>
            <div class="slide" data-background="images/img/six.jpg">
            </div>
            <div class="slide" data-background="images/img/seven.jpg">
            </div>
            <div class="slide" data-background="images/img/eight.jpg">
            </div>
        </div>
        <div class="left"></div>
        <div class="right"></div>
    </div>
</div>
<!--//Oscar end  navigation slider-->
<!--about-->
<div class="about">
    <div class="container">
        <h3 class="title">Welcome to Kitchener Master Gardeners of Ontario Inc.</h3>
        <div class="about-text">
            <div class="col-md-6 about-text-left">
                <img src="images/ab.png" class="img-responsive" alt="begonia"/>
            </div>
            <div class="col-md-6 about-text-right">
                <h4 style="font-weight:bold">KITCHENER MASTER GARDENERS</h4>
                <h4 align="justify">We are an independent non-profit organization dedicated to helping home gardeners. Master Gardeners (MGs) in the Province of Ontario are experienced gardeners who have studied horticulture extensively and continue to upgrade their skills through technical training. With this training and continuing education, Master Gardeners provide expert horticultural advice to the general public.</h4><br>
                <h4 align="justify">If you want to know where your food comes from and how it's being treated, one great solution is to grow it yourself. We can help you grow the biggest, most beautiful, pest and disease free plants.</h4>
            </div>
            <div class="clearfix"> </div>
        </div>
    </div>
    <div class="about-slid">
        <div class="container">
            <div class="about-slid-info">
                <h2><a href="http://www.mgoi.ca/education.html"><u>To become a Master Gardener</u></a></h2>
            </div>
        </div>
    </div>
</div>
<div class="about-team">
    <div class="container">
        <h3 class="title">Recommended For Beginners To Intermediate Gardeners</h3>
        <div class="row team-row">
            <div class="col-sm-6 col-md-3 team-grids">
                <div class="thumbnail team-thmnl">
                    <img src="images/i.jpg" class="img-responsive zoom-img" alt="...">
                    <div class="caption">
                        <h4><a href="#">Trainings</a></h4>
                        <p>Eight weeks of class room instruction.</p>
                    </div>
                </div>
            </div>
            <div class="col-sm-6 col-md-3 team-grids">
                <div class="thumbnail team-thmnl">
                    <img src="images/b.png" class="img-responsive zoom-img" alt="...">
                    <div class="caption">
                        <h4><a href="#">Workshops</a></h4>
                        <p>Hands-on workshops covering everything like soil preperation, seed selection, planting, maintaining, harvesting and preserving.</p>
                    </div>
                </div>
            </div>
            <div class="col-sm-6 col-md-3 team-grids">
                <div class="thumbnail team-thmnl">
                    <img src="images/e.png" class="img-responsive zoom-img" alt="...">
                    <div class="caption">
                        <h4><a href="#">Learning & Helping</a></h4>
                        <p>Learn about the gardener part in helping veggies and fruit attract the necessary pollinators and achieve their best growing potential.</p>
                    </div>
                </div>
            </div>
            <div class="col-sm-6 col-md-3 team-grids">
                <div class="thumbnail team-thmnl">
                    <img src="images/c.png" class="img-responsive zoom-img" alt="...">
                    <div class="caption">
                        <h4><a href="#">Beautiful Garden </a></h4>
                        <p>Focus is on gardens you can EAT as well as colourful and helpful companion flowers.</p>
                    </div>
                </div>
            </div>
            <div class="clearfix"> </div>
        </div>
    </div>
</div>

