<?php
$this->data["title"] = "Kitchener Master Gardeners";
$this->layout("_layout.phtml");
?>
<script>

    angular.module('myApp', ['ngRoute'])
        .config(['$routeProvider', function($routeProvider) {
            $routeProvider
            .when('/next', {
                templateUrl: 'pwd.html',
                controller: ['$scope','$routeParams', '$http', function($scope, $routeParams, $http) {
                    var pageScope = $scope.$parent;
                    var shaObj = new jsSHA("SHA-512", "TEXT");
                    shaObj.update(pageScope.sUname);
                    pageScope.uname = shaObj.getHash("HEX");
                    $http.get("/salt/" + pageScope.uname).success(function(sData){
                        pageScope.sSalt = sData.salt;
                    })
                }]
            })
            .when('/login', {
                templateUrl: 'welcome.html',
                controller: ['$scope','$routeParams', '$http', function($scope, $routeParams, $http) {
                    var pageScope = $scope.$parent;
                    var shaObj = new jsSHA("SHA-512", "TEXT");
                    shaObj.update(pageScope.uname + pageScope.sSalt + pageScope.sPassword);
                    var sSha1 = shaObj.getHash("HEX");
                    $http.get("/checklogin/" + pageScope.uname + "/" + sSha1).success(function(sData){
                        pageScope.sName = sData.name;
                        pageScope.sPassword = "";
                    })
                }]
            })
            .otherwise({
                templateUrl: 'uname.html',
                controller: ['$scope','$routeParams', '$http', function($scope, $routeParams, $http) {
                }]

            });

        }])

        .controller("myController", function ($scope, $http, $location) {
            $scope.loginsha = function(){
                $location.url("/login");
            };
            $scope.next = function(){
                $location.url("/next");
            };
    });


</script>

<!-- Top content -->
<div ng-app="myApp" ng-controller="myController" class="top-content">

    <div class="inner-bg">
        <div class="container">

            <div class="row">
                <div class="col-sm-6 col-sm-offset-3 form-box">
                    <div class="form-top">
                        <div class="form-top">
                            <h3 class="header">Members Login</h3>
                        </div>
                        <div class="form-top-right">
                            <i class="fa fa-key"></i>
                        </div>
                    </div>
                    <div class="form-bottom">
                        <center><img data-src="holder.js/40x40" src="/images/icon.jpg" class="img-circle"></center>
                        <div ng-view class="view-animate">
                        </div>
                        <script type="text/ng-template" id="uname.html">
                            <form ng-submit="next()" class="login-form" ng-cloak>
                                <div class="form-group">
                                    <input type="text" placeholder="Username ..." class="form-username form-control" ng-model="$parent.sUname">
                                </div>
                                <button type="submit" class="btn" name="Submit">Next</button>
                                <a href="contact" class="pull-right need-help"><u>Need Help</u>?</a><span class="clearfix"></span>
                            </form>
                        </script>
                        <script type="text/ng-template" id="pwd.html">
                            <form ng-submit="loginsha()" class="login-form" ng-cloak>
                                <div class="form-group">
                                    <input type="password" placeholder="Password ..." class="form-username form-control" ng-model="$parent.sPassword">
                                </div>
                                <button type="submit" class="btn" name="Submit">Login</button>
                            </form>
                        </script>
                        <script type="text/ng-template" id="welcome.html">
                                Welcome {{sName}}!
                        </script>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6 col-sm-offset-3 social-login">
                    <h4 class="signup"><a href="signup" ><u>Sign up</u></a><span class="clearfix"></span></h4>
                    <div class="social-login-buttons">
                        <a class="btn btn-link-1 btn-link-1-facebook" href="http://m.facebook.com/Kitchener-Master-Gardeners-10424583522480005">
                            <i class="fa fa-facebook"></i> Facebook
                        </a>
                        <a class="btn btn-link-1 btn-link-1-twitter" href="#">
                            <i class="fa fa-twitter"></i> Twitter
                        </a>

                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

