<?php
if(isset($_POST['btn1'])){
    $to = "kgardener2002@gmail.com"; // this is admin Email address
    $from = $_POST['email']; // this is the sender's Email address
    $first_name = $_POST['first_name'];
    $last_name = $_POST['last_name'];
    $subject = "Form submission";
    $message = $first_name . " " . $last_name . " wrote the following:" . "\n\n" . $_POST['message'];


    $headers = "From:" . $from;
    $headers2 = "From:" . $to;
    $envio = mail($to,$subject,$message,$headers);
        echo "Mail Sent. Thank you " . $first_name . ", we will contact you shortly.";
    // You can also use header('Location: thank_you.php'); to redirect to another page.

    if($envio=="true"){
        echo"the message has been sent correctly";
    }
    else{
        "there is an error sending the email";
        }

    }
?>
