<?php
$this->data["title"] = "Kitchener Master Gardeners";
$this->layout("_layout.phtml");
?>


<div class="news-info">
    <div class="container">
        <h3 class="title">OPPTURNITIES WITH KMG</h3>
    </div>
</div>
<!-- container -->
<div class="container">
    <div class="news">
        <div class="news-grids">
            <div class="col-md-4 news-grid">
                <div class="news-grid-left news-grid-left-img">
                    <h6>Volunteering For Memebers</h6>
                </div>
                <div class="news-grid-left-info">
                    <h5 style="text-align:justify;">There are a lot of volunteering opportunities for the memebers of Kitchener Master Gardeners Group.</h5>
                </div>
            </div>
            <div class="col-md-4 news-grid">
                <div class="news-grid-left news-grid-middle">
                    <h6>Tranings For Members</h6>
                </div>
                <div class="news-grid-left-info">
                    <h5 style="text-align:justify;">KMG also provides tranings programs for the memebers and others who want to become memebers.</h5>

                </div>
            </div>

            <div class="clearfix"> </div>
        </div>
    </div><!-- //container -->
</div>
<!-- //news -->





<div class="about">
            <div class="container">
                <h3 class="title">KMG Policy And Procedure</h3>
                <div class="about-text">
                    <div class="col-md-6 about-text-left">
                        <img src="images/img15.jpg" class="img-responsive" style="border: solid black 1px"; alt="begonia"/>
                    </div>
                    <div class="col-md-6 about-text-right">
                        <h4 class="widge">Latest Policy And Procedure</h4>
                        <div id="widgetmain" style="text-align:left;overflow-y:auto;overflow-x:hidden;width:100%;background-color:#FAFAA0; border:1px solid #0F9946;"><div id="rsswidget" style="height:585px;"></div><div style="text-align:right;margin-bottom:0;border-top:2px solid #0F9946;" id="widgetbottom"><span style="font-size:70%"><a href="http://www.rssfeedwidget.com">rss feed widget</a>&nbsp;</span><br></div></div>
                    </div>
                    <div class="clearfix"> </div>
                </div>
            </div>

        </div>
